"""Share command — exports a session as a self-contained HTML file."""
from __future__ import annotations

import json
import webbrowser
from pathlib import Path
from typing import Optional

SESSION_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>VectorLens Session {session_id}</title>
<style>
  :root {{
    --bg: #0f1117;
    --surface: #1a1d2e;
    --border: #2d3148;
    --text: #e2e8f0;
    --muted: #94a3b8;
    --accent: #7c3aed;
    --green: #22c55e;
    --red: #ef4444;
    --yellow: #f59e0b;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    padding: 2rem;
    line-height: 1.6;
  }}
  .header {{
    border-bottom: 1px solid var(--border);
    padding-bottom: 1rem;
    margin-bottom: 2rem;
  }}
  .header h1 {{ font-size: 1.5rem; color: var(--text); }}
  .header p {{ color: var(--muted); font-size: 0.9rem; margin-top: 0.25rem; }}
  .score-badge {{
    display: inline-block;
    padding: 0.25rem 0.75rem;
    border-radius: 9999px;
    font-weight: 600;
    font-size: 0.85rem;
    margin-top: 0.5rem;
  }}
  .score-high {{ background: #166534; color: var(--green); }}
  .score-mid {{ background: #78350f; color: var(--yellow); }}
  .score-low {{ background: #7f1d1d; color: var(--red); }}
  .section {{ margin-bottom: 2rem; }}
  .section h2 {{
    font-size: 1rem;
    font-weight: 600;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.75rem;
  }}
  .card {{
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    padding: 1rem;
    margin-bottom: 0.75rem;
  }}
  .output-text {{ white-space: pre-wrap; font-size: 0.95rem; }}
  .chunk {{ font-size: 0.875rem; }}
  .chunk-score {{
    font-size: 0.75rem;
    color: var(--muted);
    margin-top: 0.25rem;
  }}
  .hallucinated {{ border-left: 3px solid var(--red); padding-left: 0.75rem; }}
  .grounded {{ border-left: 3px solid var(--green); padding-left: 0.75rem; }}
  .footer {{
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border);
    color: var(--muted);
    font-size: 0.8rem;
  }}
</style>
</head>
<body>
<div class="header">
  <h1>VectorLens Session Report</h1>
  <p>Session ID: <code>{session_id}</code></p>
  <span class="score-badge {score_class}">
    Groundedness: {score_pct}%
  </span>
</div>

<div class="section">
  <h2>Query</h2>
  <div class="card">
    <p class="output-text">{query}</p>
  </div>
</div>

<div class="section">
  <h2>Response</h2>
  <div class="card">
    <p class="output-text">{response}</p>
  </div>
</div>

<div class="section">
  <h2>Top Chunks</h2>
  {chunks_html}
</div>

<div class="section">
  <h2>Sentence Analysis</h2>
  {sentences_html}
</div>

<div class="footer">
  Generated by VectorLens &mdash; <a href="https://github.com/Gustav-Proxi/vectorlens" style="color: var(--accent);">github.com/Gustav-Proxi/vectorlens</a>
</div>

<script>
const SESSION_DATA = {session_json};
</script>
</body>
</html>"""


def _score_class(score: float) -> str:
    if score >= 0.75:
        return "score-high"
    elif score >= 0.4:
        return "score-mid"
    return "score-low"


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def build_share_html(session: dict) -> str:
    """Build a self-contained HTML string from a session dict."""
    session_id = session.get("id", "unknown")
    query = _escape(str(session.get("query", "")))
    response = _escape(str(session.get("response", "")))
    score = float(session.get("groundedness_score", 0.0))
    score_pct = round(score * 100)

    chunks = session.get("chunks", [])[:5]
    chunks_html = ""
    for i, chunk in enumerate(chunks, 1):
        text = _escape(str(chunk.get("text", chunk if isinstance(chunk, str) else "")))
        relevance = chunk.get("relevance_score", "") if isinstance(chunk, dict) else ""
        score_line = f'<p class="chunk-score">Relevance: {relevance}</p>' if relevance != "" else ""
        chunks_html += f'<div class="card chunk"><p>#{i} {text}</p>{score_line}</div>\n'

    sentences = session.get("sentences", [])
    sentences_html = ""
    for sent in sentences:
        if isinstance(sent, dict):
            text = _escape(str(sent.get("text", "")))
            grounded = sent.get("grounded", True)
        else:
            text = _escape(str(sent))
            grounded = True
        css_class = "grounded" if grounded else "hallucinated"
        label = "✓ Grounded" if grounded else "✗ Hallucinated"
        sentences_html += f'<div class="card {css_class}"><p>{text}</p><p class="chunk-score">{label}</p></div>\n'

    return SESSION_TEMPLATE.format(
        session_id=_escape(str(session_id)),
        score_class=_score_class(score),
        score_pct=score_pct,
        query=query,
        response=response,
        chunks_html=chunks_html or "<div class='card'><p>No chunks available.</p></div>",
        sentences_html=sentences_html or "<div class='card'><p>No sentence analysis available.</p></div>",
        session_json=json.dumps(session, indent=2),
    )


def share_session(
    session: dict,
    output_path: Optional[Path] = None,
    open_browser: bool = False,
    copy_uri: bool = False,
) -> Path:
    """Export a session as a self-contained HTML file.

    Args:
        session: Session data dict.
        output_path: Path to write the HTML file. Defaults to
            ``share-<id[:8]>.html`` in the current directory.
        open_browser: If True, open the file in the default browser.
        copy_uri: If True, print the data URI to stdout (for --copy).

    Returns:
        Path to the generated HTML file.
    """
    session_id = str(session.get("id", "unknown"))
    if output_path is None:
        output_path = Path(f"share-{session_id[:8]}.html")

    html = build_share_html(session)
    output_path.write_text(html, encoding="utf-8")

    if copy_uri:
        import base64
        data_uri = "data:text/html;base64," + base64.b64encode(
            html.encode("utf-8")
        ).decode("ascii")
        print(data_uri)

    if open_browser:
        webbrowser.open(output_path.resolve().as_uri())

    return output_path